sandboxType=none
executionType=firejail

firejail=firejail
firejail.profile.execute=etc/firejail/compilers-and-tools.profile
firejail.profile.sandbox=etc/firejail/user-execution.profile
firejail.profile.wine=etc/firejail/wine.profile

cewrapper=
cewrapper.config.sandbox=etc/cewrapper/user-execution.json
cewrapper.config.execute=etc/cewrapper/compilers-and-tools.json