supportsBinary=false
supportsExecute=true
objdumper=
versionFlag=

compilers=generator
compilerType=generator
defaultCompiler=generator

compiler.generator.exe=/usr/bin/generator
compiler.generator.name=Generator